[build]
  command = "npm install --legacy-peer-deps && npm run build -- --configuration=production --output-path=dist/frontend"
  publish = "dist/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200